// tokenlean plugin for Open Code
// Generated by: tl-hook install opencode
//
// Auto-wraps wasteful bash commands with token-efficient alternatives.
// Build/test commands → tl-run (compresses output ~65%)
// curl requests → tl-browse (clean markdown output)

const BUILD_TEST_PATTERNS = [
  /\b(npm|yarn|pnpm|bun)\s+(test|run\s+test|run\s+build|run\s+lint)/,
  /\bnode\s+--test\b/,
  /\b(cargo|go)\s+(test|build|check|clippy)\b/,
  /\b(make|cmake)\b/,
  /\b(pytest|python\s+-m\s+(pytest|unittest))\b/,
  /\b(mvn|gradle)\s+(test|build|compile)\b/,
  /\b(dotnet)\s+(test|build)\b/,
  /\b(mix)\s+(test|compile)\b/,
  /\b(bundle\s+exec\s+r(spec|ake))\b/,
  /\btsc\b/,
  /\beslint\b/,
  /\bprettier\b/,
];

export const TokenleanPlugin = async () => ({
  "tool.execute.before": async (input, output) => {
    if (input.tool !== "bash") return;
    const cmd = output.args.command || "";
    if (/\btl-/.test(cmd)) return;

    // Build/test commands → wrap with tl-run
    if (BUILD_TEST_PATTERNS.some((p) => p.test(cmd))) {
      output.args.command = `tl-run "${cmd.replace(/"/g, '\\"')}"`;
      return;
    }

    // curl (non-API) → replace with tl-browse
    if (/^\s*curl\s/.test(cmd) && !/(-X\s|--data|--header.*auth|-d\s)/i.test(cmd)) {
      const urlMatch = cmd.match(/https?:\/\/\S+/);
      if (urlMatch) {
        output.args.command = `tl-browse "${urlMatch[0]}"`;
      }
    }
  },
});
